language: node_js
branches:
  only:
    - master
node_js:
  - "7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y sqlite3
install:
  - npm install
script:
  - npm run build:production
